import { registerSW as viteRegisterSW } from 'virtual:pwa-register';

/**
 * Registers the service worker generated by vite-plugin-pwa.
 * Uses `autoUpdate` strategy (configured in vite.config.ts), so the SW
 * refreshes automatically when a new build is deployed.
 */
export function registerSW(): void {
  viteRegisterSW({
    immediate: true,
    onRegisteredSW(swUrl) {
      console.info('[PWA] service worker registered:', swUrl);
    },
    onRegisterError(error) {
      console.error('[PWA] service worker registration failed:', error);
    },
  });
}
