import { VaccinationCenter } from './vaccination.types';

export const CURATED_VACCINATION_CENTERS: VaccinationCenter[] = [
  // ── BANGALORE ───────────────────────────────────────────────
  {
    id: 'vc-blr-phc-koramangala',
    name: 'Koramangala Primary Health Centre (BBMP UPHC)',
    type: 'GOVERNMENT_PHC',
    address: '8th Main Rd, 4th Block, Koramangala, Bengaluru, Karnataka 560034',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560034',
    latitude: 12.9348,
    longitude: 77.6258,
    contactPhone: '+91 80 2266 0000',
    emergencyPhone: '108',
    openingHours: '09:00 AM - 04:30 PM (Mon-Sat)',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: true,
    vaccinesAvailable: ['BCG', 'HepB-0', 'OPV-0', 'Penta-1/2/3', 'Rota-1/2/3', 'PCV', 'MMR', 'DTP', 'Tdap', 'Rabies PEP'],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.3,
    reviewsCount: 182,
    mapUrl: 'https://maps.google.com/?q=12.9348,77.6258',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.9348,77.6258',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-blr-rainbow-childrens',
    name: 'Rainbow Children’s Hospital & BirthRight Clinic',
    type: 'PEDIATRIC_CLINIC',
    address: 'Survey No. 8/5, Marathahalli - Sarjapur Outer Ring Rd, Bellandur, Bengaluru 560103',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560103',
    latitude: 12.9279,
    longitude: 77.6811,
    contactPhone: '+91 80 4241 2345',
    emergencyPhone: '+91 80 4241 9999',
    email: 'vaccinations.blr@rainbowhospitals.in',
    openingHours: '08:00 AM - 08:00 PM (Everyday)',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'BCG',
      'Penta-1/2/3 (DTaP/wP)',
      'PCV13/15',
      'Rotavirus',
      'MMR',
      'Varicella',
      'Hepatitis A',
      'Typhoid Conjugate',
      'HPV-9 Gardasil',
      'Flu Shot',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.8,
    reviewsCount: 654,
    mapUrl: 'https://maps.google.com/?q=12.9279,77.6811',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.9279,77.6811',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-blr-manipal-hospital',
    name: 'Manipal Hospital Immunization & Travel Clinic',
    type: 'PRIVATE_HOSPITAL',
    address: '98, HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560017',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560017',
    latitude: 12.9592,
    longitude: 77.6475,
    contactPhone: '+91 80 2502 4444',
    emergencyPhone: '105711',
    openingHours: '24 Hours (Dedicated Desk 08:30 AM - 07:00 PM)',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Yellow Fever (WHO Approved)',
      'HPV-9',
      'Shingrix Shingles',
      'Pneumococcal PCV20',
      'Annual Quadrivalent Flu',
      'MMR',
      'Meningococcal ACWY',
      'Rabies PEP',
    ],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.6,
    reviewsCount: 1240,
    mapUrl: 'https://maps.google.com/?q=12.9592,77.6475',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.9592,77.6475',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-blr-cloudnine-jayanagar',
    name: 'Cloudnine Hospital - Pediatric & Maternal Immunization',
    type: 'PEDIATRIC_CLINIC',
    address: '1533, 9th Main Rd, 3rd Block, Jayanagar, Bengaluru, Karnataka 560011',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560011',
    latitude: 12.9304,
    longitude: 77.5838,
    contactPhone: '+91 80 6792 9999',
    openingHours: '08:00 AM - 06:00 PM',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Penta / Hexavalent DTaP',
      'Prevnar 13',
      'Rotarix',
      'Tresivac MMR',
      'Varicella',
      'Typbar TCV',
      'Tdap',
      'Fluarix Tetra',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.7,
    reviewsCount: 890,
    mapUrl: 'https://maps.google.com/?q=12.9304,77.5838',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.9304,77.5838',
    source: 'CuratedDirectory',
  },

  // ── HYDERABAD ───────────────────────────────────────────────
  {
    id: 'vc-hyd-uphc-banjara',
    name: 'Banjara Hills Urban Primary Health Centre (GHMC)',
    type: 'GOVERNMENT_PHC',
    address: 'Road No. 12, NBT Nagar, Banjara Hills, Hyderabad, Telangana 500034',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    latitude: 17.4156,
    longitude: 78.4352,
    contactPhone: '+91 40 2111 1111',
    emergencyPhone: '108',
    openingHours: '09:00 AM - 04:00 PM (Mon-Sat)',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: true,
    vaccinesAvailable: ['BCG', 'OPV', 'Pentavalent', 'Rotavirus', 'PCV', 'MR/MMR', 'DPT', 'Tdap', 'Rabies PEP'],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.2,
    reviewsCount: 145,
    mapUrl: 'https://maps.google.com/?q=17.4156,78.4352',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=17.4156,78.4352',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-hyd-apollo-jubilee',
    name: 'Apollo Health City - Comprehensive Immunization & Travel Hub',
    type: 'PRIVATE_HOSPITAL',
    address: 'Road No. 72, Film Nagar, Jubilee Hills, Hyderabad, Telangana 500033',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    latitude: 17.4247,
    longitude: 78.4118,
    contactPhone: '+91 40 2360 7777',
    emergencyPhone: '1066',
    openingHours: '24 Hours (Vaccination Desk: 08:00 AM - 08:00 PM)',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Gardasil-9 HPV',
      'Shingrix Shingles',
      'Quadrivalent Flu Shot',
      'Yellow Fever (Authorized Govt Center)',
      'PCV15/20',
      'Hexavalent Pediatric',
      'MMR',
      'Varicella',
    ],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.8,
    reviewsCount: 1680,
    mapUrl: 'https://maps.google.com/?q=17.4247,78.4118',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=17.4247,78.4118',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-hyd-ankura-hospitals',
    name: 'Ankura Hospital for Women & Children',
    type: 'PEDIATRIC_CLINIC',
    address: 'Gachibowli - Miyapur Rd, Kothaguda, Hyderabad, Telangana 500084',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500084',
    latitude: 17.4612,
    longitude: 78.3685,
    contactPhone: '+91 90531 08108',
    openingHours: '08:30 AM - 07:30 PM',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Penta / Hexaxim',
      'Synflorix PCV',
      'Rotavac',
      'Priorix MMR',
      'Varivax',
      'Typbar TCV',
      'Hepatitis A',
      'Flu Shot',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.6,
    reviewsCount: 520,
    mapUrl: 'https://maps.google.com/?q=17.4612,78.3685',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=17.4612,78.3685',
    source: 'CuratedDirectory',
  },

  // ── MUMBAI ──────────────────────────────────────────────────
  {
    id: 'vc-mum-kem-hospital',
    name: 'King Edward Memorial (KEM) Hospital - Govt Immunization Wing',
    type: 'GOVERNMENT_PHC',
    address: 'Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400012',
    latitude: 19.0028,
    longitude: 72.8427,
    contactPhone: '+91 22 2410 7000',
    emergencyPhone: '108',
    openingHours: '08:30 AM - 04:30 PM (Mon-Sat)',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: true,
    vaccinesAvailable: ['BCG', 'HepB', 'Polio Drops & IPV', 'Pentavalent', 'Rotavirus', 'MR', 'DPT', 'Rabies Prophylaxis (24x7)'],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.4,
    reviewsCount: 940,
    mapUrl: 'https://maps.google.com/?q=19.0028,72.8427',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.0028,72.8427',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-mum-hinduja-hospital',
    name: 'P.D. Hinduja Hospital & Medical Research Centre',
    type: 'PRIVATE_HOSPITAL',
    address: 'Veer Savarkar Marg, Mahim West, Mumbai, Maharashtra 400016',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400016',
    latitude: 19.0334,
    longitude: 72.8398,
    contactPhone: '+91 22 2445 2222',
    emergencyPhone: '+91 22 2445 3333',
    openingHours: '08:00 AM - 07:00 PM',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Gardasil-9',
      'Shingrix',
      'Prevnar 20',
      'Influvac Tetra',
      'Tresivac MMR',
      'Varilrix',
      'Havrix',
      'Typhoid Conjugate',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.7,
    reviewsCount: 1420,
    mapUrl: 'https://maps.google.com/?q=19.0334,72.8398',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.0334,72.8398',
    source: 'CuratedDirectory',
  },

  // ── DELHI-NCR ───────────────────────────────────────────────
  {
    id: 'vc-del-aiims',
    name: 'All India Institute of Medical Sciences (AIIMS) Immunization Clinic',
    type: 'GOVERNMENT_PHC',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi, Delhi 110029',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110029',
    latitude: 28.5672,
    longitude: 77.2100,
    contactPhone: '+91 11 2658 8500',
    emergencyPhone: '102',
    openingHours: '08:30 AM - 04:00 PM',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: true,
    vaccinesAvailable: [
      'All Universal Immunization Programme (UIP) Vaccines',
      'Rabies PEP (24x7 Anti-Rabies Clinic)',
      'Yellow Fever Official Centre',
      'Influenza',
      'Hepatitis B',
    ],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.7,
    reviewsCount: 3200,
    mapUrl: 'https://maps.google.com/?q=28.5672,77.2100',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.5672,77.2100',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-del-fortis-vasantkunj',
    name: 'Fortis Flt. Lt. Rajan Dhall Hospital - Vaccine Center',
    type: 'PRIVATE_HOSPITAL',
    address: 'Sector B, Pocket 1, Aruna Asaf Ali Marg, Vasant Kunj, New Delhi 110070',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110070',
    latitude: 28.5303,
    longitude: 77.1568,
    contactPhone: '+91 11 4277 6222',
    openingHours: '08:00 AM - 08:00 PM',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'HPV Gardasil 9',
      'Shingrix Shingles',
      'Vaxigrip Quadrivalent',
      'Prevnar 13 / 20',
      'Infanrix Hexa',
      'Varivax',
      'M-M-R II',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.6,
    reviewsCount: 880,
    mapUrl: 'https://maps.google.com/?q=28.5303,77.1568',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.5303,77.1568',
    source: 'CuratedDirectory',
  },

  // ── CHENNAI ─────────────────────────────────────────────────
  {
    id: 'vc-chn-egmore-children',
    name: 'Institute of Child Health and Hospital for Children (Egmore)',
    type: 'GOVERNMENT_PHC',
    address: 'Halls Rd, Egmore, Chennai, Tamil Nadu 600008',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600008',
    latitude: 13.0782,
    longitude: 80.2589,
    contactPhone: '+91 44 2819 1135',
    emergencyPhone: '108',
    openingHours: '08:00 AM - 03:00 PM',
    operatingDays: 'Monday to Saturday',
    isGovtFreeUip: true,
    vaccinesAvailable: ['BCG', 'Polio Drops', 'Pentavalent', 'Rotavirus', 'PCV', 'MR/MMR', 'DPT', 'JE Vaccine'],
    walkInAllowed: true,
    appointmentRequired: false,
    rating: 4.5,
    reviewsCount: 1100,
    mapUrl: 'https://maps.google.com/?q=13.0782,80.2589',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=13.0782,80.2589',
    source: 'CuratedDirectory',
  },
  {
    id: 'vc-chn-apollo-greams',
    name: 'Apollo Children’s Hospital & Preventive Health Wing',
    type: 'PRIVATE_HOSPITAL',
    address: 'No. 15, Shafee Mohammed Rd, Thousand Lights West, Chennai 600006',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600006',
    latitude: 13.0614,
    longitude: 80.2497,
    contactPhone: '+91 44 2829 8282',
    openingHours: '08:00 AM - 07:30 PM',
    operatingDays: 'Monday to Sunday',
    isGovtFreeUip: false,
    vaccinesAvailable: [
      'Gardasil 9',
      'Shingrix',
      'Pneumosil / Prevnar',
      'Fluarix Tetra',
      'Hexaxim DTaP-IPV-HepB-Hib',
      'Priorix MMR',
      'Varilrix',
    ],
    walkInAllowed: true,
    appointmentRequired: true,
    rating: 4.7,
    reviewsCount: 760,
    mapUrl: 'https://maps.google.com/?q=13.0614,80.2497',
    directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=13.0614,80.2497',
    source: 'CuratedDirectory',
  },
];
