import { VaccineCatalogItem } from './vaccination.types';

export const VACCINE_CATALOG: VaccineCatalogItem[] = [
  // ── INFANT (0 - 12 Months) ──────────────────────────────────
  {
    id: 'vac-bcg',
    name: 'BCG (Bacillus Calmette-Guérin)',
    code: 'BCG',
    shortDescription: 'Protects against severe childhood tuberculosis and tuberculous meningitis.',
    fullDescription:
      'Live attenuated strain of Mycobacterium bovis given at birth to stimulate cellular immunity against severe pediatric manifestations of TB, including miliary TB and meningitis.',
    category: 'INFANT',
    diseasePrevented: ['Tuberculosis (TB)', 'TB Meningitis', 'Disseminated TB'],
    targetAgeDescription: 'At birth (or as early as possible within 1 year)',
    recommendedAgeMonthsMin: 0,
    recommendedAgeMonthsMax: 1,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 150, privateMax: 400 },
    administrationRoute: 'Intradermal (ID)',
    recommendedSites: ['Left upper arm / deltoid region'],
    commonSideEffects: [
      'Small red papule appearing after 2-3 weeks',
      'Small ulceration healing with permanent scar',
      'Mild localized swelling',
    ],
    precautionsAndContraindications: [
      'Do not administer to immunocompromised infants or infants with severe clinical HIV symptoms.',
      'Postpone if infant has generalized eczema or severe skin infection.',
    ],
    boosterRecommendations: 'Single lifetime dose at birth; no booster recommended in routine schedules.',
    storageTempCelsius: '+2°C to +8°C (Protect from light)',
    manufacturerBrands: ['Serum Institute BCG', 'Tubervac', 'Onco-BCG'],
  },
  {
    id: 'vac-hepb-birth',
    name: 'Hepatitis B (Birth Dose)',
    code: 'HepB-0',
    shortDescription: 'Prevents mother-to-child vertical transmission of Hepatitis B virus.',
    fullDescription:
      'Recombinant hepatitis B vaccine providing rapid active immunity against Hepatitis B infection, liver cirrhosis, and hepatocellular carcinoma.',
    category: 'INFANT',
    diseasePrevented: ['Hepatitis B Virus', 'Chronic Liver Infection', 'Liver Cirrhosis'],
    targetAgeDescription: 'Within 24 hours of birth',
    recommendedAgeMonthsMin: 0,
    recommendedAgeMonthsMax: 1,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 4,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 200, privateMax: 600 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Anterolateral aspect of mid-thigh'],
    commonSideEffects: ['Mild soreness at injection site', 'Low-grade fever', 'Fussiness'],
    precautionsAndContraindications: ['Severe allergic reaction (anaphylaxis) to previous dose or baker’s yeast.'],
    boosterRecommendations: 'Followed by primary series doses at 6, 10, and 14 weeks (or as pentavalent).',
    storageTempCelsius: '+2°C to +8°C (Do not freeze)',
    manufacturerBrands: ['GeneVac-B', 'Engerix-B', 'Elovac-B', 'B-Hepavac'],
  },
  {
    id: 'vac-opv-birth',
    name: 'Oral Polio Vaccine (OPV Zero Dose)',
    code: 'OPV-0',
    shortDescription: 'Oral live polio drops given at birth for gut mucosal immunity.',
    fullDescription:
      'Bivalent oral poliovirus vaccine drops ensuring rapid gastrointestinal mucosal immunity in neonates against type 1 and type 3 poliovirus.',
    category: 'INFANT',
    diseasePrevented: ['Poliomyelitis (Infantile Paralysis)'],
    targetAgeDescription: 'At birth (within 14 days)',
    recommendedAgeMonthsMin: 0,
    recommendedAgeMonthsMax: 1,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 4,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 100, privateMax: 250 },
    administrationRoute: 'Oral (PO)',
    recommendedSites: ['2 drops into the mouth'],
    commonSideEffects: ['Very rare mild irritability', 'Transient loose stools'],
    precautionsAndContraindications: ['Infants with severe primary immunodeficiency should receive IPV instead of OPV.'],
    boosterRecommendations: 'Routine national pulse polio drives and primary series at 6, 10, 14 weeks.',
    storageTempCelsius: '-20°C in freezer, +2°C to +8°C for short term',
    manufacturerBrands: ['Bi-Polio', 'Oral-Poliovax', 'Bio-Med OPV'],
  },
  {
    id: 'vac-penta-1',
    name: 'Pentavalent 1 (DTP-HepB-Hib)',
    code: 'Penta-1',
    shortDescription: '5-in-1 combo protecting against Diphtheria, Pertussis, Tetanus, Hep B & Hib.',
    fullDescription:
      'Combined vaccine providing active immunization against Corynebacterium diphtheriae, Bordetella pertussis, Clostridium tetani, Hepatitis B, and Haemophilus influenzae type b meningitis/pneumonia.',
    category: 'INFANT',
    diseasePrevented: [
      'Diphtheria',
      'Pertussis (Whooping Cough)',
      'Tetanus',
      'Hepatitis B',
      'Hib Pneumonia & Meningitis',
    ],
    targetAgeDescription: '6 Weeks',
    recommendedAgeMonthsMin: 1.5,
    recommendedAgeMonthsMax: 2,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 3,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 600, privateMax: 1400 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Anterolateral aspect of mid-thigh (Left)'],
    commonSideEffects: ['Moderate fever (38°C)', 'Injection site pain and redness', 'Prolonged crying for 1-2 hours'],
    precautionsAndContraindications: ['Encephalopathy within 7 days of previous pertussis vaccine.'],
    boosterRecommendations: 'Doses 2 and 3 given at 10 and 14 weeks respectively.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Pentavac PFS', 'Easyfive-TT', 'ComBE Five', 'Shan5'],
  },
  {
    id: 'vac-rotavirus-1',
    name: 'Rotavirus Vaccine (Dose 1)',
    code: 'Rota-1',
    shortDescription: 'Prevents severe dehydrating rotaviral gastroenteritis and diarrhea.',
    fullDescription:
      'Oral live attenuated or human-bovine reassortant vaccine that triggers gut IgA antibody protection against rotavirus serotypes responsible for severe acute diarrhea in infants.',
    category: 'INFANT',
    diseasePrevented: ['Severe Rotavirus Diarrhea', 'Infant Dehydration Shock'],
    targetAgeDescription: '6 Weeks',
    recommendedAgeMonthsMin: 1.5,
    recommendedAgeMonthsMax: 2,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 3,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 700, privateMax: 1800 },
    administrationRoute: 'Oral (PO)',
    recommendedSites: ['Oral drops (5 drops or 1.5ml oral applicator)'],
    commonSideEffects: ['Mild temporary diarrhea', 'Slight irritability', 'Vomiting'],
    precautionsAndContraindications: [
      'History of uncorrected congenital gastrointestinal malformation or intussusception.',
      'Severe Combined Immunodeficiency (SCID).',
    ],
    boosterRecommendations: 'Followed by Dose 2 at 10 weeks and Dose 3 at 14 weeks.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Rotavac', 'Rotateq', 'Rotasiil', 'Rotarix'],
  },
  {
    id: 'vac-pcv-1',
    name: 'Pneumococcal Conjugate Vaccine (PCV Dose 1)',
    code: 'PCV-1',
    shortDescription: 'Protects against Streptococcus pneumoniae pneumonia, sepsis, and ear infections.',
    fullDescription:
      'Conjugate polysaccharide vaccine effective against 13 to 15 virulent serotypes of Streptococcus pneumoniae causing invasive pneumococcal disease, bacteremia, and otitis media.',
    category: 'INFANT',
    diseasePrevented: ['Pneumococcal Pneumonia', 'Pneumococcal Meningitis', 'Otitis Media (Ear Infection)'],
    targetAgeDescription: '6 Weeks',
    recommendedAgeMonthsMin: 1.5,
    recommendedAgeMonthsMax: 2,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 3,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 1800, privateMax: 3800 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Anterolateral thigh (Right)'],
    commonSideEffects: ['Fever', 'Tender red swelling at injection site', 'Decreased appetite'],
    precautionsAndContraindications: ['Hypersensitivity to any component or diphtheria toxoid.'],
    boosterRecommendations: 'Dose 2 at 14 weeks, Booster at 9-12 months.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Prevnar 13', 'Synflorix', 'Pneumosil', 'Vaxneuvance (PCV15)'],
  },
  {
    id: 'vac-ipv-1',
    name: 'Inactivated Polio Vaccine (Fractional IPV Dose 1)',
    code: 'fIPV-1',
    shortDescription: 'Injectable killed polio vaccine for systemic humoral immunity against all 3 types.',
    fullDescription:
      'Inactivated trivalent poliovirus vaccine stimulating high serum neutralising antibody titers without any risk of vaccine-derived paralytic polio.',
    category: 'INFANT',
    diseasePrevented: ['Poliovirus Types 1, 2, and 3'],
    targetAgeDescription: '6 Weeks & 14 Weeks',
    recommendedAgeMonthsMin: 1.5,
    recommendedAgeMonthsMax: 2,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 450, privateMax: 1100 },
    administrationRoute: 'Intradermal (ID)',
    recommendedSites: ['Right upper arm (deltoid)'],
    commonSideEffects: ['Transient local redness and swelling', 'Mild fever'],
    precautionsAndContraindications: ['Known severe allergy to streptomycin, neomycin, or polymyxin B.'],
    boosterRecommendations: 'Second fractional dose at 14 weeks.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Imovax Polio', 'Polprotec', 'ShanIPV'],
  },
  {
    id: 'vac-penta-2',
    name: 'Pentavalent 2 (DTP-HepB-Hib)',
    code: 'Penta-2',
    shortDescription: 'Second dose of the 5-in-1 combo immunization.',
    fullDescription:
      'Second primary dose strengthening immune memory against Diphtheria, Pertussis, Tetanus, Hepatitis B, and Hib.',
    category: 'INFANT',
    diseasePrevented: ['Diphtheria', 'Pertussis', 'Tetanus', 'Hepatitis B', 'Hib'],
    targetAgeDescription: '10 Weeks',
    recommendedAgeMonthsMin: 2.5,
    recommendedAgeMonthsMax: 3,
    dosesCount: 1,
    doseNumber: 2,
    totalDosesInSeries: 3,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 600, privateMax: 1400 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Anterolateral aspect of mid-thigh (Left)'],
    commonSideEffects: ['Low to moderate fever', 'Injection site swelling', 'Temporary irritability'],
    precautionsAndContraindications: ['Encephalopathy within 7 days of previous dose.'],
    boosterRecommendations: 'Final primary dose at 14 weeks.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Pentavac PFS', 'Easyfive-TT', 'Shan5'],
  },
  {
    id: 'vac-penta-3',
    name: 'Pentavalent 3 (DTP-HepB-Hib)',
    code: 'Penta-3',
    shortDescription: 'Third primary dose completing the infant 5-in-1 foundational series.',
    fullDescription:
      'Final dose of the primary infant pentavalent series delivering over 95% protective antibody levels against all 5 pathogens.',
    category: 'INFANT',
    diseasePrevented: ['Diphtheria', 'Pertussis', 'Tetanus', 'Hepatitis B', 'Hib'],
    targetAgeDescription: '14 Weeks',
    recommendedAgeMonthsMin: 3.5,
    recommendedAgeMonthsMax: 4,
    dosesCount: 1,
    doseNumber: 3,
    totalDosesInSeries: 3,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 600, privateMax: 1400 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Anterolateral aspect of mid-thigh (Left)'],
    commonSideEffects: ['Fever', 'Soreness at injection site'],
    precautionsAndContraindications: ['Acute febrile illness (defer until recovery).'],
    boosterRecommendations: 'DTP Booster 1 recommended at 16-24 months.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Pentavac PFS', 'Easyfive-TT', 'Shan5'],
  },
  {
    id: 'vac-mmr-1',
    name: 'MR / MMR Vaccine (Dose 1)',
    code: 'MMR-1',
    shortDescription: 'Protects against Measles, Mumps, and Rubella (German Measles).',
    fullDescription:
      'Live attenuated triple viral vaccine that prevents high-fever measles rash with respiratory and neurological complications, painful mumps parotitis, and congenital rubella syndrome.',
    category: 'INFANT',
    diseasePrevented: ['Measles', 'Mumps', 'Rubella (German Measles)', 'Congenital Rubella Syndrome'],
    targetAgeDescription: '9 - 12 Months',
    recommendedAgeMonthsMin: 9,
    recommendedAgeMonthsMax: 12,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 450, privateMax: 1200 },
    administrationRoute: 'Subcutaneous (SC)',
    recommendedSites: ['Right upper arm (deltoid subcutaneous tissue)'],
    commonSideEffects: [
      'Mild fever occurring 5-12 days post-vaccination',
      'Transient faint measles-like rash',
      'Swelling of salivary glands (rare)',
    ],
    precautionsAndContraindications: [
      'Severe primary immunodeficiency, active leukemia, or high-dose systemic corticosteroid therapy.',
      'Pregnancy (live vaccine).',
    ],
    boosterRecommendations: 'Dose 2 administered at 15-18 months (or 4-6 years).',
    storageTempCelsius: '+2°C to +8°C (Reconstituted vaccine used within 4 hours)',
    manufacturerBrands: ['Tresivac', 'M-M-R II', 'Priorix', 'Serum Institute MR'],
  },

  // ── EARLY CHILDHOOD (1 - 6 Years) ───────────────────────────
  {
    id: 'vac-varicella-1',
    name: 'Varicella (Chickenpox Dose 1)',
    code: 'VAR-1',
    shortDescription: 'Prevents Varicella Zoster virus chickenpox blisters and scarring.',
    fullDescription:
      'Live attenuated Oka strain vaccine inducing durable T-cell and B-cell immunity against chickenpox and its secondary bacterial complications.',
    category: 'CHILD',
    diseasePrevented: ['Chickenpox (Varicella)', 'Secondary Skin Infections', 'Varicella Pneumonia'],
    targetAgeDescription: '15 Months',
    recommendedAgeMonthsMin: 15,
    recommendedAgeMonthsMax: 18,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 1500, privateMax: 2400 },
    administrationRoute: 'Subcutaneous (SC)',
    recommendedSites: ['Outer aspect of upper arm'],
    commonSideEffects: ['Slight fever', 'Mild rash with a few vesicles at injection site'],
    precautionsAndContraindications: ['Immunodeficiency or immunosuppressive therapy.'],
    boosterRecommendations: 'Dose 2 at 4 - 6 years of age.',
    storageTempCelsius: '-50°C to -15°C (Reconstitute immediately before injection)',
    manufacturerBrands: ['Varilrix', 'Varivax', 'Bio-Varicella'],
  },
  {
    id: 'vac-hepa-1',
    name: 'Hepatitis A Vaccine (Dose 1)',
    code: 'HepA-1',
    shortDescription: 'Prevents water-borne and food-borne acute viral hepatitis liver infection.',
    fullDescription:
      'Inactivated or live attenuated Hepatitis A virus vaccine conferring lifelong protection against epidemic jaundice and acute liver failure.',
    category: 'CHILD',
    diseasePrevented: ['Hepatitis A', 'Acute Jaundice', 'Acute Liver Failure'],
    targetAgeDescription: '12 - 15 Months',
    recommendedAgeMonthsMin: 12,
    recommendedAgeMonthsMax: 18,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 1200, privateMax: 2200 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Local tenderness', 'Headache', 'Mild fever'],
    precautionsAndContraindications: ['Severe allergy to aluminium or previous dose.'],
    boosterRecommendations: 'Dose 2 given 6 months after Dose 1.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Havrix 720 Junior', 'Avaxim 80', 'Biovac-A', 'Vaqta'],
  },
  {
    id: 'vac-dtp-booster-1',
    name: 'DTP Booster 1 (Diphtheria, Tetanus, Pertussis)',
    code: 'DTP-B1',
    shortDescription: 'First childhood booster reinforcing protection before preschool years.',
    fullDescription:
      'Adsorbed diphtheria, tetanus toxoids, and whole-cell or acellular pertussis vaccine ensuring sustained antibody levels across early childhood.',
    category: 'CHILD',
    diseasePrevented: ['Diphtheria', 'Tetanus', 'Whooping Cough (Pertussis)'],
    targetAgeDescription: '16 - 24 Months',
    recommendedAgeMonthsMin: 16,
    recommendedAgeMonthsMax: 24,
    dosesCount: 1,
    doseNumber: 4,
    totalDosesInSeries: 5,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 350, privateMax: 1500 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Left mid-thigh or left deltoid'],
    commonSideEffects: ['Painful swelling at site', 'Fever > 38.5°C', 'Malaise'],
    precautionsAndContraindications: ['Hypotonic-hyporesponsive episodes following prior pertussis vaccine.'],
    boosterRecommendations: 'DTP Booster 2 at 5 - 6 years.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Triple Antigen DTP', 'Infanrix (DTaP)', 'Quadrovac'],
  },
  {
    id: 'vac-typhoid-conjugate',
    name: 'Typhoid Conjugate Vaccine (TCV)',
    code: 'TCV',
    shortDescription: 'Single-dose conjugate protection against Salmonella Typhi enteric fever.',
    fullDescription:
      'Vi capsular polysaccharide conjugated to tetanus toxoid protein carrier providing robust T-dependent long-term immunity in children older than 6 months.',
    category: 'CHILD',
    diseasePrevented: ['Typhoid Fever', 'Enteric Salmonellosis', 'Intestinal Perforation'],
    targetAgeDescription: '9 - 12 Months',
    recommendedAgeMonthsMin: 9,
    recommendedAgeMonthsMax: 12,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 1200, privateMax: 2000 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle or anterolateral thigh'],
    commonSideEffects: ['Mild swelling at injection site', 'Low-grade fever for 24h'],
    precautionsAndContraindications: ['Hypersensitivity to tetanus toxoid.'],
    boosterRecommendations: 'Single dose provides protection for at least 5-7 years; optional booster at age 5-6.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Typbar TCV', 'PedaTyph', 'Zyvac TCV'],
  },
  {
    id: 'vac-dtp-booster-2',
    name: 'DTP Booster 2 (School Entry)',
    code: 'DTP-B2',
    shortDescription: 'School-entry booster defending against respiratory pertussis and tetanus.',
    fullDescription:
      'Pre-school immunization booster critical for sustaining community herd immunity in classrooms against whooping cough outbreaks and tetanus exposure from outdoor play.',
    category: 'CHILD',
    diseasePrevented: ['Diphtheria', 'Tetanus', 'Pertussis'],
    targetAgeDescription: '5 - 6 Years',
    recommendedAgeMonthsMin: 60,
    recommendedAgeMonthsMax: 72,
    dosesCount: 1,
    doseNumber: 5,
    totalDosesInSeries: 5,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 350, privateMax: 1600 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Local soreness', 'Mild fatigue', 'Low fever'],
    precautionsAndContraindications: ['History of immediate anaphylaxis.'],
    boosterRecommendations: 'Followed by Tdap/Td booster at age 10 and 16 years.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['DPT Vaccine Serum Institute', 'Infanrix', 'Tripacel'],
  },

  // ── ADOLESCENT (7 - 18 Years) ────────────────────────────────
  {
    id: 'vac-hpv-9',
    name: 'HPV Vaccine (Human Papillomavirus 9-Valent)',
    code: 'HPV-9',
    shortDescription: 'Prevents cervical, anal, and throat cancers caused by high-risk HPV strains.',
    fullDescription:
      'Recombinant vaccine against oncogenic HPV types 16, 18, 31, 33, 45, 52, 58 (causing 90% of cervical cancers) and low-risk types 6 & 11 (genital warts). Highly recommended for adolescents aged 9-14.',
    category: 'ADOLESCENT',
    diseasePrevented: ['Cervical Cancer', 'Anal Cancer', 'Oropharyngeal Cancer', 'Genital Warts'],
    targetAgeDescription: '9 - 14 Years (2-dose schedule) / 15-26 Years (3 doses)',
    recommendedAgeMonthsMin: 108,
    recommendedAgeMonthsMax: 168,
    dosesCount: 2,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 2800, privateMax: 9500 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Pain and redness at injection site', 'Dizziness / fainting (syncope - sit for 15 min)', 'Mild headache'],
    precautionsAndContraindications: ['Severe allergy to yeast. Not recommended during active pregnancy.'],
    boosterRecommendations: '2 doses at 0 and 6 months for ages 9-14; 3 doses (0, 2, 6 months) for age 15+.',
    storageTempCelsius: '+2°C to +8°C (Do not freeze)',
    manufacturerBrands: ['Gardasil 9', 'Gardasil 4', 'Cervavac (Serum Institute)', 'Cervarix'],
  },
  {
    id: 'vac-tdap-adolescent',
    name: 'Tdap / Td Booster (Tetanus, reduced Diphtheria, Acellular Pertussis)',
    code: 'Tdap-10',
    shortDescription: 'Protects adolescents against tetanus injuries and waning whooping cough immunity.',
    fullDescription:
      'Reduced antigen formulation designed for adolescents and adults to refresh protective antibodies against tetanus wounds and reduce transmission of pertussis to newborn family members.',
    category: 'ADOLESCENT',
    diseasePrevented: ['Tetanus', 'Diphtheria', 'Pertussis'],
    targetAgeDescription: '10 - 12 Years & 16 Years',
    recommendedAgeMonthsMin: 120,
    recommendedAgeMonthsMax: 144,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 500, privateMax: 1400 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Arm stiffness/pain for 24-48 hours', 'Mild headache', 'Tiredness'],
    precautionsAndContraindications: ['Guillain-Barré syndrome within 6 weeks of a prior tetanus toxoid.'],
    boosterRecommendations: 'Booster recommended every 10 years throughout adulthood.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Boostrix', 'Adacel', 'Td-Vac'],
  },

  // ── ADULT & SENIOR (19 - 65+ Years) ──────────────────────────
  {
    id: 'vac-flu-annual',
    name: 'Influenza Vaccine (Quadrivalent Annual Flu Shot)',
    code: 'FLU-ANNUAL',
    shortDescription: 'Annual seasonal protection against 4 circulating influenza A & B virus strains.',
    fullDescription:
      'Updated yearly to match WHO-recommended strains for Northern/Southern hemisphere winters, preventing severe flu pneumonia, hospitalization, and cardiovascular stress in adults and high-risk groups.',
    category: 'ADULT',
    diseasePrevented: ['Seasonal Influenza A (H1N1, H3N2)', 'Influenza B (Victoria & Yamagata)', 'Secondary Flu Pneumonia'],
    targetAgeDescription: 'Annual dose for all adults, pregnant women, and elderly 50+',
    recommendedAgeMonthsMin: 228,
    recommendedAgeMonthsMax: 1200,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 900, privateMax: 2100 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Soreness at injection site', 'Mild myalgia / body ache for 1-2 days', 'Low-grade fever'],
    precautionsAndContraindications: ['Severe anaphylaxis to egg protein (cell-based alternatives available).'],
    boosterRecommendations: 'Repeat annually ahead of flu season (September-October or April-May in tropics).',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Fluarix Tetra', 'Vaxigrip Tetra', 'Influvac Tetra', 'Fluzone Quadrivalent'],
  },
  {
    id: 'vac-shingles',
    name: 'Recombinant Zoster (Shingles Vaccine - Shingrix)',
    code: 'RZV-SHINGRIX',
    shortDescription: 'Over 90% protection against painful Herpes Zoster shingles and nerve neuralgia.',
    fullDescription:
      'Recombinant adjuvanted glycoprotein E vaccine preventing reactivation of dormant varicella zoster virus in sensory dorsal root ganglia, drastically reducing agonizing post-herpetic neuralgia in adults 50+.',
    category: 'SENIOR',
    diseasePrevented: ['Herpes Zoster (Shingles)', 'Post-Herpetic Neuralgia (PHN)', 'Ophthalmic Zoster'],
    targetAgeDescription: 'Adults aged 50+ years and immunocompromised adults 19+',
    recommendedAgeMonthsMin: 600,
    recommendedAgeMonthsMax: 1200,
    dosesCount: 2,
    doseNumber: 1,
    totalDosesInSeries: 2,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 8500, privateMax: 13500 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Significant local muscle soreness', 'Fatigue and shivering', 'Headache for 24-48 hours'],
    precautionsAndContraindications: ['Current active shingles outbreak (wait until symptoms fully resolve).'],
    boosterRecommendations: '2-dose series given 2 to 6 months apart. Lifelong protection.',
    storageTempCelsius: '+2°C to +8°C (Do not freeze)',
    manufacturerBrands: ['Shingrix (GSK)'],
  },
  {
    id: 'vac-pcv20-senior',
    name: 'Pneumococcal 20-Valent / PPSV23 (Adult & Senior)',
    code: 'PCV20-SR',
    shortDescription: 'Prevents life-threatening bacteremic pneumococcal pneumonia in older adults.',
    fullDescription:
      'Expanded conjugate vaccine providing comprehensive protection against 20 capsular serotypes responsible for severe geriatric pneumonia, bacteremia, and chronic pulmonary exacerbations.',
    category: 'SENIOR',
    diseasePrevented: ['Invasive Pneumococcal Disease', 'Bacteremic Pneumonia', 'Pneumococcal Sepsis'],
    targetAgeDescription: 'All adults aged 65+ and adults 19-64 with asthma, diabetes, or heart conditions',
    recommendedAgeMonthsMin: 780,
    recommendedAgeMonthsMax: 1200,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 0, privateMin: 3200, privateMax: 5500 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Pain at injection site', 'Joint pain', 'Mild fever'],
    precautionsAndContraindications: ['Hypersensitivity to any component or diphtheria toxoid.'],
    boosterRecommendations: 'Single dose of PCV20 replaces older sequential PCV13+PPSV23 protocols.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Prevnar 20 (Apexxnar)', 'Pneumovax 23'],
  },
  {
    id: 'vac-covid-booster',
    name: 'COVID-19 XBB / JN.1 Updated Booster',
    code: 'COVID-BOOST',
    shortDescription: 'Updated sublineage booster restoring neutralization against circulating Omicron variants.',
    fullDescription:
      'Protein subunit or mRNA updated booster designed to prevent severe COVID-19 hospitalization, long COVID symptoms, and microvascular complications in vulnerable adults.',
    category: 'ADULT',
    diseasePrevented: ['Severe COVID-19 Disease', 'SARS-CoV-2 Acute Respiratory Distress', 'Long COVID'],
    targetAgeDescription: 'Annual or 6-month booster for high risk, seniors 60+, and healthcare workers',
    recommendedAgeMonthsMin: 216,
    recommendedAgeMonthsMax: 1200,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: false,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 400, privateMax: 1800 },
    administrationRoute: 'Intramuscular (IM)',
    recommendedSites: ['Deltoid muscle of upper arm'],
    commonSideEffects: ['Arm soreness', 'Low fever and body aches for 24 hours', 'Lymph node tenderness'],
    precautionsAndContraindications: ['History of myocarditis following prior mRNA dose without clearance.'],
    boosterRecommendations: 'Recommended every 12 months for high-risk elderly and immunocompromised individuals.',
    storageTempCelsius: '+2°C to +8°C or -80°C depending on platform',
    manufacturerBrands: ['Corbevax', 'Covishield (AstraZeneca)', 'Novavax / Nuvaxovid', 'Comirnaty'],
  },

  // ── SPECIAL & TRAVEL VACCINES ────────────────────────────────
  {
    id: 'vac-yellow-fever',
    name: 'Yellow Fever Vaccine (17D Live Attenuated)',
    code: 'YFV-17D',
    shortDescription: 'Mandatory international travel vaccine for endemic African and South American regions.',
    fullDescription:
      'Live viral vaccine giving 99% lifelong protection against mosquito-borne yellow fever virus. Administered exclusively at authorized Yellow Fever Vaccination Centers with official WHO Yellow Card stamped.',
    category: 'SPECIAL_TRAVEL',
    diseasePrevented: ['Yellow Fever Virus', 'Hemorrhagic Fever Shock', 'Hepatorenal Failure'],
    targetAgeDescription: 'Travelers aged 9 months to 59 years visiting endemic zones',
    recommendedAgeMonthsMin: 9,
    recommendedAgeMonthsMax: 708,
    dosesCount: 1,
    doseNumber: 1,
    totalDosesInSeries: 1,
    isMandatory: false,
    isUipGovernmentFree: false,
    estimatedCostInr: { government: 300, privateMin: 1800, privateMax: 3500 },
    administrationRoute: 'Subcutaneous (SC)',
    recommendedSites: ['Deltoid upper arm'],
    commonSideEffects: ['Mild flu-like headache and low fever at 3-7 days', 'Myalgia'],
    precautionsAndContraindications: [
      'Severe allergy to eggs or gelatin.',
      'Thymus disorders or severe immunodeficiency.',
      'Infants under 6 months old.',
    ],
    boosterRecommendations: 'Single dose provides lifetime validity according to WHO International Health Regulations.',
    storageTempCelsius: '+2°C to +8°C',
    manufacturerBrands: ['Stamaril (Sanofi Pasteur)', 'Kasauli CRI Yellow Fever'],
  },
  {
    id: 'vac-rabies-pep',
    name: 'Rabies Vaccine (Purified Chick Embryo / Vero Cell - PEP Series)',
    code: 'RAB-PEP',
    shortDescription: 'Life-saving post-exposure prophylaxis following animal bites or scratches.',
    fullDescription:
      'Purified Vero Cell / PCECV inactivated rabies vaccine providing 100% fatal encephalitis prevention when administered immediately on days 0, 3, 7, and 14-28 following category II/III animal exposure.',
    category: 'SPECIAL_TRAVEL',
    diseasePrevented: ['Rabies Encephalitis (100% fatal without prophylaxis)'],
    targetAgeDescription: 'Any age immediately upon animal bite/scratch exposure',
    recommendedAgeMonthsMin: 0,
    recommendedAgeMonthsMax: 1200,
    dosesCount: 4,
    doseNumber: 1,
    totalDosesInSeries: 4,
    isMandatory: true,
    isUipGovernmentFree: true,
    estimatedCostInr: { government: 0, privateMin: 350, privateMax: 800 },
    administrationRoute: 'Intramuscular (IM) / Intradermal (ID)',
    recommendedSites: ['Deltoid muscle (never in gluteal region)'],
    commonSideEffects: ['Local soreness', 'Mild fever', 'Headache'],
    precautionsAndContraindications: ['NO CONTRAINDICATIONS for post-exposure prophylaxis due to 100% fatality of rabies.'],
    boosterRecommendations: 'Post-exposure protocol on Day 0, 3, 7, and 14 (plus Rabies Immunoglobulin for Category III bites).',
    storageTempCelsius: '+2°C to +8°C (Never freeze)',
    manufacturerBrands: ['Rabivax-S', 'Rabipur', 'Abhayrab', 'Verorab'],
  },
];
